### ISSUE TITLE
Unable to initialize libMPV

### ISSUE THREAD

**Issue by VandJ** [varianus/ovom3u#1]
Can you please tell me how to get rid of this error "Unable to initialize libMPV"?

**Comment by varianus** [comment]
If the error message is "Can''t initialize libMPV", it means that libmpv shared library in not available on your system or it have an unsupported version

If "Unable to initialize libMPV" is the exact error message,  it's not coming from my application, maybe directly from libmpv.

If you tell me which OS  are you using, i could try to help on libmpv installation.

**Comment by VandJ** [comment]
Thanks for the answer.
OS Windows 10.

**Comment by VandJ** [comment]
<a href="https://ibb.co/CQ8Y5G2"><img src="https://i.ibb.co/CQ8Y5G2/1.png" alt="1" border="0"></a>

**Comment by varianus** [comment]
Sorry for the delay, got some hardware issues.

For Windows  you can find pre-built libMPV binaries at [SourceForge](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/).

The last version i've tested is this one (32 bit): [https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-i686-20210613-git-03b9f8e.7z/download](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-i686-20210613-git-03b9f8e.7z/download).

Extract from the downloaded 7zip archive the file named **mpv-1.dll** (about 70 Mb) into the same folder of the ovom3u executable.  If you are using the default project options it should be in sub-folder called "bin" in the source folder.

You could also put the dll in a folder listed in your PATH environment variable.

**Comment by VandJ** [comment]
Thanks a lot, MPV works great with this version.

**Comment by alas82** [comment]
actually still showing the same message even i followed your previous instruction , can you provide exe copy of it
